### PR TITLE
Ignore project coverage

### PR DESCRIPTION
**Pull request by akaszynski**
Seems that even with #907, codecov doesn't like negative project coverage changes. This PR completely removes the project coverage CI reports and will only fail on patch < 90%.

@maxcapodi78, do you feel that 90% on new features is too high, or should be go lower than that?

### CODE REVIEW

**Comment by maxcapodi78** [comment]
@akaszynski  Let's keep 90% for new code but on existing code is though to reach. I would use 85% for now and increase it as soon as the overall rate is around that percentage

**Review by maxcapodi78 — APPROVED** [review]

**Review by MaxJPRey — APPROVED** [review]

**Comment by akaszynski** [comment]
Don't merge quite yet. I'll be lowering to 85 and completely skipping the project check all together.

**Comment by Alberto-DM** [comment]
@akaszynski Try to merge the main. We did lot of improvements on the unit tests.

**Comment by akaszynski** [comment]
Finally working! Merging, thanks for the hint @Alberto-DM!

**Pull request merged**
