### PR TITLE
Fix/solution type

### PR DESCRIPTION
**Pull request by maxcapodi78**

### CODE REVIEW

**Comment by MaxJPRey** [comment]
LGTM

**Review by MaxJPRey — APPROVED** [review]

**Comment by kbhagat-ansys** [comment]
Still seeing issues with 22.1. Taking it offline with @maxcapodi78

**Comment by kbhagat-ansys** [comment]
If you are seeing the tests Pass, then please merge it and then I will test after it  has merged.  There are certanly some places where the default version number can be extracted from 1 place. I see a few places where the version number is being got from different locations

**Review by kbhagat-ansys — APPROVED** [review]

**Comment by kbhagat-ansys** [comment]
I was able to get IronPython unit test passing in 22.1 but I had to change the version in 2 places. 
`run_unittests.py`
image
and add a `local_config.json` pointing to 22.1. there is room for improvement to consolidate/derive the versions when running form within IronPython

**Pull request merged**
