### PR TITLE
add icons

### PR DESCRIPTION
**Pull request by jsalant22**
add icons for the emit examples

### CODE REVIEW

**Comment by jsalant22** [comment]
These are the icons that will be displayed on this page: https://aedt.docs.pyansys.com/release/0.6/examples/07-EMIT/index.html

**Comment by myoung301** [comment]
@maxcapodi78 - I see the doc build was successful. Is there a way to view the build output so we can see how the example page will look before merging?

CC @jsalant22

**Comment by maxcapodi78** [comment]
> @maxcapodi78 - I see the doc build was successful. Is there a way to view the build output so we can see how the example page will look before merging?
> 
> CC @jsalant22

The pyaedt documentation is published on https://aedt.docs.pyansys.com/version/stable/examples/index.html. Here you can find all examples including Emit published examples

The Dev documentaion doesn't build the examples  since it takes too much

**Comment by myoung301** [comment]
Ok - I guess we need to push this in and then see what it looks like and adjust with another PR, if needed.

**Review by myoung301 — APPROVED** [review]

**Pull request merged**
