### PR TITLE
circle void issues fixed

### PR DESCRIPTION
**Pull request by svandenb-dev**

### CODE REVIEW

**Review by maxcapodi78 — CHANGES_REQUESTED** [review]
Please fix the documentation and add unit test.
LGTM

**Comment by MaxJPRey** [comment]
LGTM.

**Review by MaxJPRey — APPROVED** [review]

**Review by svandenb-dev — COMMENTED** [review]
fixed

**Review by maxcapodi78 — APPROVED** [review]
LGTM

**Pull request merged**
