### PR TITLE
Additional flake8 checks

### PR DESCRIPTION
**Pull request by jleonatti**
- Adds checks for whitespace after commas and around operators. 
- Adds check for `import *` module imports. 
- Cleans up all instances of `import *`. 
- Removes doc/source/examples directory from flake8 check, since this is .gitignore as well.

### CODE REVIEW

**Comment by akaszynski** [comment]
Curious, ci-build isn't showing up here.

**Comment by jleonatti** [comment]
@akaszynski any idea what the issue is with the doc build?
```

Sphinx parallel build error:
NameError: name 'warnings' is not defined
make: *** [Makefile:25: html] Error 2
make: Leaving directory '/home/runner/work/PyAEDT/PyAEDT/doc'
```

It is most likely a module import issue from something I changed, but it isn't clear to me where the module is trying to be imported from.

**Comment by akaszynski** [comment]
Documentation build is on Linux and it seems that the module can't be imported within Linux.  I'm pushing a minor change that checks to see if we can first import the module to make the docbuild easier to debug.

**Review by akaszynski — APPROVED** [review]
LGTM.

**Pull request merged**
