### PR TITLE
added extra dependcies, eg pip install pyaedt[all]

### LINKED ISSUE #1308: Bug located in ...Iron python import pyadet error due to numpy
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Iron python import pyadet error due to numpy

pyadet version: main branch
numpy version: 1.21.6

error message:

```
  File "c:\users\byang\desktop\pyaedt_numpy\venv\lib\site-packages\numpy\__init__.py", line 132
            raise ImportError(msg) from e

                                   ^
SyntaxError: unexpected token 'from'
```

Both cpython and ironpython are used in aedt test framework. And ironpython is not compatible with numpy version 1.21.6.

We want to install some minimal packages like this: 
`pip install pyaedt[minimal] `

and this will install only pyaedt + COM interfaces

### Steps To Reproduce

- create venv (python 3.7)
- pip install git+https://github.com/pyansys/pyaedt.git@main
- launch ironpython
- run:
  ```python
  import sys
  sys.path.append(r"c:\users\byang\desktop\pyaedt_numpy\venv\lib\site-packages")
  import pyaedt
  ```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

ironpython

### PR DESCRIPTION
**Pull request by beliaev-maksim**
same as pyvista PR https://github.com/pyvista/pyvista/pull/2826

closes #1308

### CODE REVIEW

**Comment by maxcapodi78** [comment]
@beliaev-maksim all the requirements you put in extras we consider now mandatory for pyaedt CPython because are needed for many pre and post processing operations. I'm not sure is a good idea to revert them to optional and exclude them from installation only because of Ironpython. @akaszynski what do you think about it?

**Comment by beliaev-maksim** [comment]
@maxcapodi78 
the problem is that if you do not use post processing installing numpy and matplotlib and other deps is too heavy. And this is not only because of IronPython.
For general AEDT interface none of these libraries is required

**Comment by akaszynski** [comment]
> @akaszynski what do you think about it?

I think the idea behind having optional dependencies is a good one; not everyone is going to want to install additional dependencies. However, I would prefer that we do this the other way around; we have a "light" install option where users can choose to not install the heavy dependencies, but we default to installing them.

**Comment by maxcapodi78** [comment]
> > @akaszynski what do you think about it?
> 
> I think the idea behind having optional dependencies is a good one; not everyone is going to want to install additional dependencies. However, I would prefer that we do this the other way around; we have a "light" install option where users can choose to not install the heavy dependencies, but we default to installing them.

That's is a good idea!

**Pull request closed without merging**
