### PR TITLE
Organize module imports

### PR DESCRIPTION
**Pull request by jleonatti**
Organize module imports and remove unused imports with the hopes of adding this check to the flake8 config once all refactoring is complete.

### CODE REVIEW

**Comment by akaszynski** [comment]
These seem to be sorted to. Is that the case?

**Comment by jleonatti** [comment]
> These seem to be sorted to. Is that the case?

Yes, I organized them too while I was at it, but this isn't enforced by flake8.

**Review by akaszynski — APPROVED** [review]
Thanks for going though this.

**Comment by akaszynski** [comment]
Merging to give europe and east coast a fresh start for Monday.

**Pull request merged**
