### PR TITLE
Import 1D and 3D dataset method 

### PR DESCRIPTION
**Pull request by Samuelopez-ansys**
Import dataset method

### CODE REVIEW

**Comment by Samuelopez-ansys** [comment]
Hi @MaxJPRey ,

The test is failing to install pyaedt, please could you help to identify the issue?

Thanks

**Comment by MaxJPRey** [comment]
> Hi @MaxJPRey ,
> 
> The test is failing to install pyaedt, please could you help to identify the issue?
> 
> Thanks

The issue was the pip install option `--use-feature=in-tree-build` removed which was preventing the installation of the pyaedt package. @maxcapodi78 fixed it.

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys If possible, can you add more info in the title of the PR as it is used in the release notes.

**Comment by MaxJPRey** [comment]
> @Samuelopez-ansys If possible, can you add more info in the title of the PR as it is used in the release notes.

Thanks @Samuelopez-ansys .

**Pull request merged**
