### PR TITLE
Fixes to component creation

### PR DESCRIPTION
**Pull request by seeyouatcloudbase**

### CODE REVIEW

**Comment by Samuelopez-ansys** [comment]
Hi @MaxJPRey , please could you check why is failing the Style Check? 

Thanks!

**Comment by Samuelopez-ansys** [comment]
Hi @maxcapodi78 , 

Dave implemented 2 new methods, and we realized 'create_new_component_from_symbol' was duplicated in 2 different classes 'PrimitivesNexxim' and 'PrimitivesCircuit'. After a check, I removed it from Primitives Circuit.

In addition, this method was not cover by the unittest, and @seeyouatcloudbase add a new unittest. Could you verify the duplicate method was a error?

Thanks

**Comment by MaxJPRey** [comment]
@Samuelopez-ansys I am looking at the style check issue.

**Comment by Samuelopez-ansys** [comment]
Thanks @MaxJPRey , for next PR, how could we know where the style check is failing? I didn't find where was the issue... thanks

**Review by Samuelopez-ansys — APPROVED** [review]

**Pull request merged**
