### PR TITLE
Test35 ironpython

### PR DESCRIPTION
**Pull request by koubaa**
Support test 35 in ironpython

### CODE REVIEW

**Comment by akaszynski** [comment]
Looks like iron python failed in #463 in https://github.com/pyansys/PyAEDT/runs/3622763506.  @maxcapodi78, any idea why these errors aren't being reported in the action?

Sorry for the approval, saw the green checkmark didn't realize that test failures wouldn't be displayed.  We need to fix that.

**Comment by koubaa** [comment]
> Looks like iron python failed in #463 in https://github.com/pyansys/PyAEDT/runs/3622763506. @maxcapodi78, any idea why these errors aren't being reported in the action?
> 
> Sorry for the approval, saw the green checkmark didn't realize that test failures wouldn't be displayed. We need to fix that.

@akaszynski  Massimo was going to take care of that in his next push (and I also fixed it here)

**Comment by maxcapodi78** [comment]
@akaszynski the ironphyton unit test cicd is fault tolerant because ironphyton is more unstable than cpython. furthermore one modification made in previous PR made failing all tests. I've fixed that and now tests looks much better

**Comment by koubaa** [comment]
> @akaszynski the ironphyton unit test cicd is fault tolerant because ironphyton is more unstable than cpython. furthermore one modification made in previous PR made failing all tests. I've fixed that and now tests looks much better

@maxcapodi78 It should be possible give an indicator about failing tests in PRs without automatically blocking PRs because of it

**Comment by maxcapodi78** [comment]
that would be great. let's talk tomorrow morning

**Review by maxcapodi78 — APPROVED** [review]
LGTM

**Pull request merged**
